name: GitHub Pages deploy
on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: GH Pages deploy
      uses: Cecilapp/GitHub-Pages-deploy@3.2.1
